config templating added using handlebar
Kong/workspace-config-apply-nodejs pull request #3
Opened 2021-06-29 19:41 UTC by avik-sengupta-kong

config templating added using handlebar

2021-06-29 19:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/workspace-config-apply-nodejs?pullRequest=3) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/workspace-config-apply-nodejs?pullRequest=3) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/workspace-config-apply-nodejs?pullRequest=3) it.</sub>

2021-06-29 20:25 UTC, srb3 requested changes

2021-06-29 20:25 UTC, srb3 commented on config/workspace-data.json
> +        "name": "hsbc-zeta",
minor point: public repo lets not use company names

2021-06-29 20:25 UTC, srb3 commented on config/workspace-data.json
> +        "name": "hsbc-eta",
same here

2021-06-29 20:25 UTC, srb3 commented on app.js
> +const handlebars= require('handlebars');
shall we include a space before the '=' to keep it consistent

2021-06-29 20:25 UTC, srb3 commented on app.js
> +    let configHbs='./config/workspace-template.hbs'
consistent spacing

2021-06-30 09:00 UTC, avik-sengupta-kong commented
All requested changes addressed.

2021-06-30 14:15 UTC, avik-sengupta-kong commented
No longer relevant.

2021-06-30 14:15 UTC, closed without merging